In [2]:
import pandas as pd

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
df.head()

Shape: (7043, 21)

Columns: ['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [9]:
df = df.dropna(subset=['TotalCharges'])

In [10]:
print("\nDuplicates:", df.duplicated().sum())

Duplicates: 0

In [11]:
df['SeniorCitizen'] = df['SeniorCitizen'].map({1: 'Senior', 0: 'Non-Senior'})

print("\nCleaned shape:", df.shape)
df.head()

Cleaned shape: (7032, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,Non-Senior,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,Non-Senior,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,Non-Senior,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,Non-Senior,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,Non-Senior,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [12]:
def tenure_group(tenure):
    if tenure <= 12:
        return '0-12 Months'
    elif tenure <= 24:
        return '13-24 Months'
    elif tenure <= 48:
        return '25-48 Months'
    else:
        return '49+ Months'

df['Tenure_Group'] = df['tenure'].apply(tenure_group)

print("Tenure groups added:")
print(df['Tenure_Group'].value_counts())

Tenure groups added:
Tenure_Group
49+ Months      2239
0-12 Months     2175
25-48 Months    1594
13-24 Months    1024
Name: count, dtype: int64

In [13]:
total = len(df)
churned = df[df['Churn'] == 'Yes'].shape[0]
retained = df[df['Churn'] == 'No'].shape[0]
churn_rate = round(churned / total * 100, 2)

print(f"Total Customers: {total}")
print(f"Churned: {churned}")
print(f"Retained: {retained}")
print(f"Churn Rate: {churn_rate}%")

Total Customers: 7032
Churned: 1869
Retained: 5163
Churn Rate: 26.58%

In [14]:
contract_churn = df.groupby(['Contract', 'Churn']).size().reset_index(name='Count')
print("Churn by Contract Type:")
print(contract_churn)

Churn by Contract Type:
         Contract Churn  Count
0  Month-to-month    No   2220
1  Month-to-month   Yes   1655
2        One year    No   1306
3        One year   Yes    166
4        Two year    No   1637
5        Two year   Yes     48

In [15]:
tenure_churn = df.groupby(['Tenure_Group', 'Churn']).size().reset_index(name='Count')
print("Churn by Tenure Group:")
print(tenure_churn)

Churn by Tenure Group:
   Tenure_Group Churn  Count
0   0-12 Months    No   1138
1   0-12 Months   Yes   1037
2  13-24 Months    No    730
3  13-24 Months   Yes    294
4  25-48 Months    No   1269
5  25-48 Months   Yes    325
6    49+ Months    No   2026
7    49+ Months   Yes    213

In [16]:
internet_churn = df.groupby(['InternetService', 'Churn']).size().reset_index(name='Count')
print("Churn by Internet Service:")
print(internet_churn)

Churn by Internet Service:
  InternetService Churn  Count
0             DSL    No   1957
1             DSL   Yes    459
2     Fiber optic    No   1799
3     Fiber optic   Yes   1297
4              No    No   1407
5              No   Yes    113

In [17]:
payment_churn = df.groupby(['PaymentMethod', 'Churn']).size().reset_index(name='Count')
print("Churn by Payment Method:")
print(payment_churn)

Churn by Payment Method:
               PaymentMethod Churn  Count
0  Bank transfer (automatic)    No   1284
1  Bank transfer (automatic)   Yes    258
2    Credit card (automatic)    No   1289
3    Credit card (automatic)   Yes    232
4           Electronic check    No   1294
5           Electronic check   Yes   1071
6               Mailed check    No   1296
7               Mailed check   Yes    308

In [18]:
avg_charges = df.groupby('Churn')['MonthlyCharges'].mean().reset_index()
avg_charges.columns = ['Churn', 'Avg_Monthly_Charges']
avg_charges['Avg_Monthly_Charges'] = avg_charges['Avg_Monthly_Charges'].round(2)
print("Avg Monthly Charges by Churn:")
print(avg_charges)

Avg Monthly Charges by Churn:
  Churn  Avg_Monthly_Charges
0    No                61.31
1   Yes                74.44

In [19]:
senior_churn = df.groupby(['SeniorCitizen', 'Churn']).size().reset_index(name='Count')
print("Churn by Senior Citizen:")
print(senior_churn)

Churn by Senior Citizen:
  SeniorCitizen Churn  Count
0    Non-Senior    No   4497
1    Non-Senior   Yes   1393
2        Senior    No    666
3        Senior   Yes    476

In [20]:
tableau_columns = [
    'customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
    'tenure', 'Tenure_Group', 'PhoneService', 'InternetService',
    'Contract', 'PaperlessBilling', 'PaymentMethod',
    'MonthlyCharges', 'TotalCharges', 'Churn'
]

df_tableau = df[tableau_columns]
df_tableau.to_csv('churn_cleaned.csv', index=False)

print(f"✅ churn_cleaned.csv saved!")
print(f"Shape: {df_tableau.shape}")
df_tableau.head()

✅ churn_cleaned.csv saved!
Shape: (7032, 15)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,Tenure_Group,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,Non-Senior,Yes,No,1,0-12 Months,No,DSL,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,Non-Senior,No,No,34,25-48 Months,Yes,DSL,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,Non-Senior,No,No,2,0-12 Months,Yes,DSL,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,Non-Senior,No,No,45,25-48 Months,No,DSL,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,Non-Senior,No,No,2,0-12 Months,Yes,Fiber optic,Month-to-month,Yes,Electronic check,70.70,151.65,Yes